version: v1.1.0
steps:
  - cmd: |
      token=$(az acr login -n bifirmStagingRegistry --expose-token --output tsv --query "accessToken") && \
      az acr manifest list-metadata -r bifirmStagingRegistry -n partner --orderby time_desc --output tsv --query "[?createdTime < '2025-02-01T00:00:00Z'].digest" | \
      xargs -I {} az acr repository delete --name bifirmStagingRegistry --image partner@{} --yes
    image: mcr.microsoft.com/azure-cli
    timeout: 3600
triggers:
  - timer:
      schedule: "00 14 11 3 *"
      timezone: "GMT"
